name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'develop'
      - 'workflow-fixes'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install latest Yarn
        run: corepack prepare yarn@stable --activate

      - name: Activate latest Yarn
        run: yarn set version stable

      - name: Install Yarn dependencies
        run: yarn install

      - name: Verify Yarn workspaces and their dependencies
        run: yarn dlx @yarnpkg/doctor .

      - name: Build Yarn packages
        run: yarn workspaces foreach --topological-dev --all --exclude @martinaeynl/ui-docs-storybook run build
        
      #- name: Build
      #  uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      #  with:
      #    install_command: yarn install
      #    build_command: yarn build
      #    path: dev/apps/storybook/dist
